@PORT=3000
@HOST = http://localhost:{{PORT}}

GET {{HOST}}/api/usuarios
Authorization: API-KEY

###
GET {{HOST}}/api/usuarios/2
Authorization: API-KEY

###
POST {{HOST}}/api/usuarios
Authorization: API-KEY
Content-Type: application/json

{
  "nombre_autor":"Jorge",
  "imagen_autor":"https://thispersondoesnotexist.com/",
  "email_autor":"Jorge@gmail.com"
}
###
PUT {{HOST}}/api/usuarios/1
Authorization: API-KEY
Content-Type: application/json

{
  "nombre_autor":"Madona",
  "imagen_autor":"https://thispersondoesnotexist.com/",
  "email_autor":"justi@gmail.com"
}
###
DELETE {{HOST}}/api/usuarios


//empiezo rutas de publicaciones
###
GET {{HOST}}/api/publicaciones
Authorization: API-KEY


###
GET {{HOST}}/api/publicaciones/2
Authorization: API-KEY

###
POST {{HOST}}/api/publicaciones/
Authorization: API-KEY
Content-Type: application/json

{
  "titulo": "ESCALADFA",
  "descripcion": "LA MONTAÑA",
  "fecha": "2024-02-12",
  "autores_idautores": 1,
  "categorias_idcategorias1":2
}
###
PUT {{HOST}}/api/publicaciones/10
Authorization: API-KEY
Content-Type: application/json

{
  "titulo": "BARILOCHE",
  "descripcion": "NOS FUIMOS A BARILO, y al cerro catedral",
  "fecha": "2023-05-12",
  "categorias_idcategorias1":1
}