@PORT=3000
@HOST = http://localhost:{{PORT}}

GET {{HOST}}/api/usuarios
Authorization: API-KEY

###
GET {{HOST}}/api/usuarios/1
Authorization: API-KEY

###
POST {{HOST}}/api/usuarios
Authorization: API-KEY
Content-Type: application/json

{
  "nombre_autor":"Daniel",
  "imagen_autor":"https://thispersondoesnotexist.com/",
  "email_autor":"daniel@gmail.com"
}
###
PUT {{HOST}}/api/usuarios/1
Authorization: API-KEY
Content-Type: application/json

{
  "nombre_autor":"Daniel Guillermo",
  "imagen_autor":"https://thispersondoesnotexist.com/",
  "email_autor":"daniel@gmail.com"
}




//empiezo rutas de publicaciones
###
GET {{HOST}}/api/publicaciones
Authorization: API-KEY


###
GET {{HOST}}/api/publicaciones/1
Authorization: API-KEY

###
POST {{HOST}}/api/publicaciones/
Authorization: API-KEY
Content-Type: application/json

{
  "titulo": "ESCALADA",
  "descripcion": "LA MONTAÑA",
  "fecha": "2024-02-12",
  "categoria":"DEPORTE",
  "autores_idautores": 1
}
###
PUT {{HOST}}/api/publicaciones/20
Authorization: API-KEY
Content-Type: application/json

{
  "titulo": "ESCALADA",
  "descripcion": "LA MONTAÑA",
  "fecha": "2024-02-12",
  "categoria":"DEPORTE",
  "autores_idautores": 1,
}


